DIGITAL TICKET & RECEIPT - MISA CINEMA
Thank you for choosing MisaCinema!

TICKET CODE: MC-<?= str_pad((string)$booking->id, 6, '0', STR_PAD_LEFT) ?>
(Sila tunjukkan kod ini kepada staff di pintu masuk)

Movie Title: <?= h($booking->show->show_title) ?>
Show Date: <?= $booking->show->show_date instanceof \DateTimeInterface ? $booking->show->show_date->format('d M Y') : $booking->show->show_date ?>
Showtime: <?= ($booking->show->show_time instanceof \DateTimeInterface) ? $booking->show->show_time->format('h:i A') : $booking->show->show_time ?>
Cinema Hall: <?= $booking->has('hall') ? h($booking->hall->hall_type) : 'Standard Hall' ?>
Seats: <?= $booking->quantity ?> Seat(s) (<?= h($booking->seat_selection) ?>)

TOTAL PAID: RM <?= number_format((float)$booking->ticket_price, 2) ?>
Paid via <?= h($booking->payments[0]->payment_method ?? 'Online Banking') ?>

This is an automated receipt generated by MisaCinema.
ENJOY YOUR MOVIE!
